### ISSUE TITLE
No way to specify language in CSS classes in superfences

### ISSUE THREAD

**Issue by lukesneeringer** [facelessuser/pymdown-extensions#996] opened 2020-06-26 22:06 UTC
Ideally, I would like to capture the language at the beginning of a fence:

~~~
```language
~~~

And convert it to something that I can code against (for making slight JavaScript tweaks, for example):

```
<pre class="highlight lang-language">
  <code>
  ...
  </code>
</pre>
```

The `css_class` option seems to only let me hard-code text, and while it looks potentially possible to do something like this with a custom fence, that seems like a _lot_ of work for what seems like a small item.

It would be nice if there could be substitutions: let us specify `{language}` and have it be replaced with the appropriate value.

**Comment by facelessuser** [comment] 2020-06-26 22:15
This is literally what it does. What are you getting instead? Did you disable Pygments?

Here is a test that shows behavior: https://github.com/facelessuser/pymdown-extensions/blob/master/tests/test_extensions/test_highlight.py#L112.

This is according to the HTML5 spec: https://www.w3.org/TR/html52/textlevel-semantics.html#the-code-element.

**Comment by facelessuser** [comment] 2020-06-29 19:37
Ping. Just seeing if you can provide more info or if I need to close this?

**Closed** 2020-07-03 20:33 UTC
Labels: S: more-info-needed, S: triage

**Comment by lukesneeringer** [comment] 2020-07-05 22:12
I see `class="highlight"` but no `language-XYZ` equivalent.

**Comment by facelessuser** [comment] 2020-07-05 22:59
I need you to provide your configuration and some example content or I cannot help. Let me know if you have Pygments installed as well.

All of my docs are generates with these intentions, and they are fully tested work a test suite, so I know the generally work. So if you are having difficulty, you have to provide sufficient information for me to reproduce.

**Comment by choishingwan** [comment] 2020-08-03 09:29
I have similar problem. My mkdocs.yml has the following:

```
theme: readthedocs
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.tabbed
    - pymdownx.superfences
    - pymdownx.highlight:
        use_pygments: True
    - toc:
        permalink: True
    - codehilite
    - pymdownx.arithmatex:
        generic: True
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret

extra_css:
  - css/extra.css
  - css/details.css

google_analytics:
    - 'UA-145068952-1'
    - auto

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - javascripts/details.js
```

My software versions are 
Python: 3.7.2.
Pygments           2.6.1
pymdown-extensions 7.1
mkdocs             1.1.2


If I type

 \```python 
 import numpy as np
\```

The resulting html display is
\<div class="highlight">\<pre>\<span>\</span>\<code class="hljs coffeescript">\<span class="kn">\<span class="hljs-keyword">import\</span>\</span> \<span class="nn">numpy\</span> \<span class="k">\<span class="hljs-keyword">as\</span>\</span> \<span class="nn">np\</span>
\</code>\</pre>\</div>

which is strange considering the the code class is hljs coffeescript instead of python

and if I change my mkdocs.yml to 
```
theme: 
    name: readthedocs
    highlightjs: false
```

The html code changes to 
\<div class="highlight">\<pre>\<span>\</span>\<code>\<span class="kn">import\</span> \<span class="nn">numpy\</span> \<span class="k">as\</span> \<span class="nn">np\</span>
\</code>\</pre>\</div>

where the there isn't any class for the code attribute. 

Did I missed something important when I use pymdonwx.highlight or are there any 

The only highlight related css in my extra.css is
```

.highlight pre{ 
    white-space: pre-wrap;
    overflow: auto;
    box-sizing: border-box;
    margin: 0 !important;
    padding: 0em 0em !important;
    border: 1px solid #CCC !important;
    border-top-width: 1px;
    border-bottom-width: 1px;
    border-top-style: solid;
    border-bottom-style: solid;
    border-top-color: #CCC;
    border-bottom-color: #CCC;
    border-image-source: none;
    border-image-slice: 100% 100% 100% 100%;
    border-image-width: 1 1 1 1;
    border-image-outset: 0 0 0 0;
    border-image-repeat: stretch stretch;
    position: static
}
```


Thank you for your time and awesome package!

**Comment by facelessuser** [comment] 2020-08-03 12:17
Your issue is not the same. It looks like you are trying to use highlight.js, but are not turning off Pygments. If you use Pygments, it will highlight your code instead of highlight.js. Turn off Pygments if you'd like to use highlight.js.

**Comment by choishingwan** [comment] 2020-08-03 12:32
Thanks. I'd like to use pygments and I thought I can disable highlight.js
using the highlightjs: False option under theme. What's the proper way of
disabling highlight.js in favour of Pygmnets?

Have tried using
theme:
    name: readthedocs
    highlightjs: False

markdown_extensions:
    - pymdownx.highlight:
        use_pygments: True

yet that doesn't seems to work
Thank you!

**Comment by facelessuser** [comment] 2020-08-03 12:39
That would be a mkdocs theme thing. I don't know what the theme does, I can only control whether pygments gets used or not.

From your initial post, it looks like Pygments was parsing the content. When Pygments parses a code block, there will be no language class as it is no longer needed, the content is already parsed. Only JavaScript highlighters need a language class on the `code` element.

So, what it looks like is happening is that Pygments parses the content, and then highlight.js, which is still enabled, trys to guess the language and assigns coffescript to the code block.

**Comment by facelessuser** [comment] 2020-08-03 12:42
Also, this may be helpful, but I don't know if you can capitilize `True`	 and `False` in yaml configs. I think they should be lower case.

**Comment by choishingwan** [comment] 2020-08-03 13:15
Thank you so much for your help!

I ended up make it work by using noclasses: true. It didn't work otherwise.

Thank you for your help!
