### ISSUE TITLE
magiclinks creates nested links when pre-existing HTML exists within markdown

### ISSUE THREAD

**Issue by 4oo4** [facelessuser/pymdown-extensions#2223] opened 2023-10-31 22:14 UTC
### Description

I'm using magiclinks to render markdown that has some prerendered HTML, and in cases where I already have a link rendered and the link text is the same as the URL, magiclinks creates a nested link.

Since having HTML within markdown is still considered valid markdown, could magiclinks recognize when text is between an `<a>...</a>` tag (already HTML) and not try to render it a second time?

Most of the time this would be an invisible problem but in certain cases I've noticed it incorrectly renders a link when it encounters `[…]` in link text because of the way the Slack API shortens URLs.

## Example 1:
```python
import markdown

text = '''
# example markdown
- blah
- blah

<a href="https://example.com">https://example.com</a>
'''
html = markdown.markdown(text, extensions=['pymdownx.magiclink'])
print(html)
```
Result:
```html
<h1>example markdown</h1>\n<ul>\n<li>blah</li>\n<li>blah</li>\n</ul>\n<p><a href="https://example.com"><a href="https://example.com">https://example.com</a></a></p>
```

## Example 2:
```python
import markdown

text = '<a href="https://example.com/some/very/long/link/that/gets/truncated/but/this/is/longer/and/not/shortened?param=blahblahblahblah">https://example.com/some/very/long/link/that/gets/truncated[…]?param=blahblahblahblah</a>'

html = markdown.markdown(text, extensions=['pymdownx.magiclink'])
print(html)

```
Result:

```html
<p><a href="https://example.com/some/very/long/link/that/gets/truncated/but/this/is/longer/and/not/shortened?param=blahblahblahblah"><a href="https://example.com/some/very/long/link/that/gets/truncated">https://example.com/some/very/long/link/that/gets/truncated</a>[…]?param=blahblahblahblah</a></p>
```

### Version(s) & System Info

- Operating System: Debian 12
- Python Version: 3.11.2
- Package Version: 10.3.1

**Comment by facelessuser** [comment] 2023-10-31 22:34
I can understand this being a problem, but unfortunately, it is a known issue.

The solution would be that if the parent is an `<a>` tag that we should not apply the inline parser that transforms links. Unfortunately, that context is unavailable at the time of parsing.

**Comment by facelessuser** [comment] 2023-10-31 22:36
Keep in mind, this is not just a MagicLink issue, this is true for links of any kind in Python Markdown.

```py
>>> import markdown
>>> markdown.markdown('<a href="https://example.com"><https://example.com></a>')
'<p><a href="https://example.com"><a href="https://example.com">https://example.com</a></a></p>'
```

I've toyed with the idea of potentially tagging each "magic" anchor we manipulate, and then adding a treeprocessor to search for and undo any we've done that have a parent of `<a>`.  It adds more overhead, but it is probably the only way I can think of that could potentially solve the issue. Keep in mind that Markdown does this with all links.

**Comment by 4oo4** [comment] 2023-11-01 16:40
Thanks for the explanation, however with the couple examples I'm seeing different behavior with Python Markdown and magiclink.

When I ran example 1 with just Python Markdown, it does not create nested links when the link text isn't between angle brackets, while magiclink creates nested links in both cases:
```python
>>> import markdown
>>> text = '<a href="https://example.com">https://example.com</a>'
>>> markdown.markdown(text)
'<p><a href="https://example.com">https://example.com</a></p>'

>>> text = '<a href="https://example.com"><https://example.com></a>'
>>> markdown.markdown(text)
'<p><a href="https://example.com"><a href="https://example.com">https://example.com</a></a></p>'

>>> text = '<a href="https://example.com"><https://example.com></a>'
>>> markdown.markdown(text, extensions=['pymdownx.magiclink'])
'<p><a href="https://example.com"><a href="https://example.com">https://example.com</a></a></p>'

>>> text = '<a href="https://example.com">https://example.com</a>'
>>> markdown.markdown(text, extensions=['pymdownx.magiclink'])
'<p><a href="https://example.com"><a href="https://example.com">https://example.com</a></a></p>'

```
With example 2, I also noticed that Python Markdown also correctly wraps the link text and is also different behavior from magiclink.

```python
>>> text = '<a href="https://example.com/some/very/long/link/that/gets/truncated/but/this/is/longer/and/not/shortened?param=blahblahblahblah">https://example.com/some/very/long/link/that/gets/truncated[…]?param=blahblahblahblah</a>'
>>> markdown.markdown(text)
'<p><a href="https://example.com/some/very/long/link/that/gets/truncated/but/this/is/longer/and/not/shortened?param=blahblahblahblah">https://example.com/some/very/long/link/that/gets/truncated[…]?param=blahblahblahblah</a></p>'

>>> text = '<a href="https://example.com/some/very/long/link/that/gets/truncated/but/this/is/longer/and/not/shortened?param=blahblahblahblah">https://example.com/some/very/long/link/that/gets/truncated[…]?param=blahblahblahblah</a>'
>>> markdown.markdown(text, extensions=['pymdownx.magiclink'])
'<p><a href="https://example.com/some/very/long/link/that/gets/truncated/but/this/is/longer/and/not/shortened?param=blahblahblahblah"><a href="https://example.com/some/very/long/link/that/gets/truncated">https://example.com/some/very/long/link/that/gets/truncated</a>[…]?param=blahblahblahblah</a></p>'
```

**Comment by facelessuser** [comment] 2023-11-01 17:23
You are misunderstanding what I'm saying. Python Markdown uses uses notations like `<ulr>` or `[text](url)`. My point is that they do not exclude turning Markdown URLs into links even if their parent is already a link.

**Comment by facelessuser** [comment] 2023-11-10 21:39
This is basically a duplicate of: https://github.com/facelessuser/pymdown-extensions/issues/1074. This issue was resolved as a `wontfix` when originally evaluated.

Since Python Markdown does not provide us with parent context, and hides the raw HTML tags so we cannot see them in the treeprocessor, there is nothing we can do.

I would discourage users use raw links as you've done if using Magiclink or live with the odd double linking.

**Closed** 2023-11-10 21:53 UTC
Labels: T: bug, S: triage
