### ISSUE TITLE
Minor trouble with magiclink extension

### ISSUE THREAD

**Issue by Andre601** [facelessuser/pymdown-extensions#866] opened 2020-03-28 14:02 UTC
I try to implement the MagicLink extension into my sites, but when using it, does it not shorten the github urls, despite me enabling both `repo_url_shortener` and `repo_url_shorthand` in the mkdocs.yml

I want to point out, that the repositories I want to point towards are all on GitHub, but not all are within the same organisation/user.

The extension does automatically set the link, but does not shorten it in any way.
`@user/repo` mentions are working, but do lack the GitHub icon. Does this require the provider to be set?
Or does it require some additional CSS stuff to be added?

I'm generally lost on how I could implement this the best way.

Additional information:
- Version MkDocs 1.1
- Using Material Theme 5.0.0 RC 3
- Using PyMdown 7.0 with following extensions:
  - superfences
  - tabbed
  - magiclink

**Comment by facelessuser** [comment] 2020-03-28 14:26
@Andre601 I need examples. Config, example user names that aren't working etc.

My tests all show that this works as expected and I even demonstrate various examples in the docs:  https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/

@gir-bot remove S: triage
@gir-bot add S: more-info-needed

**Comment by Andre601** [comment] 2020-03-28 14:32
mkdocs.yml
https://gist.github.com/Andre601/67e05f24a686f2dd8be4a7ed656f2db4#file-mkdocs-yml

credits.md
https://gist.github.com/Andre601/67e05f24a686f2dd8be4a7ed656f2db4#file-credits-md

Rendered page:
![image](https://user-images.githubusercontent.com/11576465/77825394-4dac4000-7109-11ea-859c-217334c3eb63.png)

Would I require to also include the emoji extension, for having those icons?

**Comment by facelessuser** [comment] 2020-03-28 15:21
So, it would appear we shorten issues, commits, comparisons, but we don't shorten repos and users. I think this is indeed a oversight on my part. You can specify `@squidfund/mkdocs-material` and it will link it for you, it just doesn't shorten `https://github.com/squidfunk/mkdocs-material`, but I think it should, so I can look into this.

---

The icons are just special CSS styling. You can use this CSS (I think I got it all):

```css
.md-typeset a[href^="mailto:"]::before {
  -webkit-mask-image: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><path d='M20,4H4C2.89,4 2,4.89 2,6V18A2,2 0 0,0 4,20H20A2,2 0 0,0 22,18V6C22,4.89 21.1,4 20,4M17,17H7V15H17M17,13H7V11H17M20,9H17V6H20' /></svg>");
          mask-image: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><path d='M20,4H4C2.89,4 2,4.89 2,6V18A2,2 0 0,0 4,20H20A2,2 0 0,0 22,18V6C22,4.89 21.1,4 20,4M17,17H7V15H17M17,13H7V11H17M20,9H17V6H20' /></svg>"); }

.md-typeset .magiclink-compare::before,
.md-typeset .magiclink-commit::before,
.md-typeset .magiclink-pull::before,
.md-typeset .magiclink-issue::before {
  -webkit-mask-position: bottom;
          mask-position: bottom;
  -webkit-mask-repeat: no-repeat;
          mask-repeat: no-repeat;
  -webkit-mask-size: 0.9375em auto;
          mask-size: 0.9375em auto; }

.md-typeset .magiclink-repository::before,
.md-typeset .magiclink-compare::before,
.md-typeset .magiclink-commit::before,
.md-typeset .magiclink-pull::before,
.md-typeset .magiclink-issue::before,
.md-typeset a[href^="mailto:"]::before {
  position: relative;
  width: 1em;
  height: 1em;
  padding-right: 1em;
  background-color: var(--md-primary-fg-color);
  background-size: 1em;
  transition: background-color 125ms;
  content: "\a0"; }

.md-typeset .magiclink-repository:hover::before,
.md-typeset .magiclink-compare:hover::before,
.md-typeset .magiclink-commit:hover::before,
.md-typeset .magiclink-pull:hover::before,
.md-typeset .magiclink-issue:hover::before,
.md-typeset a[href^="mailto:"]:hover::before {
  background-color: var(--md-accent-fg-color); }

.md-typeset .magiclink-commit::before {
  -webkit-mask-image: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' width='14' height='16' viewBox='0 0 14 16'><path fill-rule='evenodd' d='M10.86 7c-.45-1.72-2-3-3.86-3-1.86 0-3.41 1.28-3.86 3H0v2h3.14c.45 1.72 2 3 3.86 3 1.86 0 3.41-1.28 3.86-3H14V7h-3.14zM7 10.2c-1.22 0-2.2-.98-2.2-2.2 0-1.22.98-2.2 2.2-2.2 1.22 0 2.2.98 2.2 2.2 0 1.22-.98 2.2-2.2 2.2z'/></svg>");
          mask-image: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' width='14' height='16' viewBox='0 0 14 16'><path fill-rule='evenodd' d='M10.86 7c-.45-1.72-2-3-3.86-3-1.86 0-3.41 1.28-3.86 3H0v2h3.14c.45 1.72 2 3 3.86 3 1.86 0 3.41-1.28 3.86-3H14V7h-3.14zM7 10.2c-1.22 0-2.2-.98-2.2-2.2 0-1.22.98-2.2 2.2-2.2 1.22 0 2.2.98 2.2 2.2 0 1.22-.98 2.2-2.2 2.2z'/></svg>"); }

.md-typeset .magiclink-compare::before {
  -webkit-mask-image: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' width='13' height='16' viewBox='0 0 13 16'><path fill-rule='evenodd' d='M6 7h2v1H6v2H5V8H3V7h2V5h1v2zm-3 6h5v-1H3v1zM7.5 2L11 5.5V15c0 .55-.45 1-1 1H1c-.55 0-1-.45-1-1V3c0-.55.45-1 1-1h6.5zM10 6L7 3H1v12h9V6zM8.5 0H3v1h5l4 4v8h1V4.5L8.5 0z'/></svg>");
          mask-image: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' width='13' height='16' viewBox='0 0 13 16'><path fill-rule='evenodd' d='M6 7h2v1H6v2H5V8H3V7h2V5h1v2zm-3 6h5v-1H3v1zM7.5 2L11 5.5V15c0 .55-.45 1-1 1H1c-.55 0-1-.45-1-1V3c0-.55.45-1 1-1h6.5zM10 6L7 3H1v12h9V6zM8.5 0H3v1h5l4 4v8h1V4.5L8.5 0z'/></svg>"); }

.md-typeset .magiclink-pull::before {
  -webkit-mask-image: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' width='12' height='16' viewBox='0 0 12 16'><path fill-rule='evenodd' d='M11 11.28V5c-.03-.78-.34-1.47-.94-2.06C9.46 2.35 8.78 2.03 8 2H7V0L4 3l3 3V4h1c.27.02.48.11.69.31.21.2.3.42.31.69v6.28A1.993 1.993 0 0010 15a1.993 1.993 0 001-3.72zm-1 2.92c-.66 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2zM4 3c0-1.11-.89-2-2-2a1.993 1.993 0 00-1 3.72v6.56A1.993 1.993 0 002 15a1.993 1.993 0 001-3.72V4.72c.59-.34 1-.98 1-1.72zm-.8 10c0 .66-.55 1.2-1.2 1.2-.65 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2zM2 4.2C1.34 4.2.8 3.65.8 3c0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2z'/></svg>");
          mask-image: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' width='12' height='16' viewBox='0 0 12 16'><path fill-rule='evenodd' d='M11 11.28V5c-.03-.78-.34-1.47-.94-2.06C9.46 2.35 8.78 2.03 8 2H7V0L4 3l3 3V4h1c.27.02.48.11.69.31.21.2.3.42.31.69v6.28A1.993 1.993 0 0010 15a1.993 1.993 0 001-3.72zm-1 2.92c-.66 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2zM4 3c0-1.11-.89-2-2-2a1.993 1.993 0 00-1 3.72v6.56A1.993 1.993 0 002 15a1.993 1.993 0 001-3.72V4.72c.59-.34 1-.98 1-1.72zm-.8 10c0 .66-.55 1.2-1.2 1.2-.65 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2zM2 4.2C1.34 4.2.8 3.65.8 3c0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2z'/></svg>"); }

.md-typeset .magiclink-issue::before {
  -webkit-mask-image: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' width='14' height='16' viewBox='0 0 14 16'><path fill-rule='evenodd' d='M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 011.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z'/></svg>");
          mask-image: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' width='14' height='16' viewBox='0 0 14 16'><path fill-rule='evenodd' d='M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 011.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z'/></svg>"); }

.md-typeset .magiclink-repository.magiclink-github::before {
  -webkit-mask-image: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><path d='M12,2A10,10 0 0,0 2,12C2,16.42 4.87,20.17 8.84,21.5C9.34,21.58 9.5,21.27 9.5,21C9.5,20.77 9.5,20.14 9.5,19.31C6.73,19.91 6.14,17.97 6.14,17.97C5.68,16.81 5.03,16.5 5.03,16.5C4.12,15.88 5.1,15.9 5.1,15.9C6.1,15.97 6.63,16.93 6.63,16.93C7.5,18.45 8.97,18 9.54,17.76C9.63,17.11 9.89,16.67 10.17,16.42C7.95,16.17 5.62,15.31 5.62,11.5C5.62,10.39 6,9.5 6.65,8.79C6.55,8.54 6.2,7.5 6.75,6.15C6.75,6.15 7.59,5.88 9.5,7.17C10.29,6.95 11.15,6.84 12,6.84C12.85,6.84 13.71,6.95 14.5,7.17C16.41,5.88 17.25,6.15 17.25,6.15C17.8,7.5 17.45,8.54 17.35,8.79C18,9.5 18.38,10.39 18.38,11.5C18.38,15.32 16.04,16.16 13.81,16.41C14.17,16.72 14.5,17.33 14.5,18.26C14.5,19.6 14.5,20.68 14.5,21C14.5,21.27 14.66,21.59 15.17,21.5C19.14,20.16 22,16.42 22,12A10,10 0 0,0 12,2Z' /></svg>");
          mask-image: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><path d='M12,2A10,10 0 0,0 2,12C2,16.42 4.87,20.17 8.84,21.5C9.34,21.58 9.5,21.27 9.5,21C9.5,20.77 9.5,20.14 9.5,19.31C6.73,19.91 6.14,17.97 6.14,17.97C5.68,16.81 5.03,16.5 5.03,16.5C4.12,15.88 5.1,15.9 5.1,15.9C6.1,15.97 6.63,16.93 6.63,16.93C7.5,18.45 8.97,18 9.54,17.76C9.63,17.11 9.89,16.67 10.17,16.42C7.95,16.17 5.62,15.31 5.62,11.5C5.62,10.39 6,9.5 6.65,8.79C6.55,8.54 6.2,7.5 6.75,6.15C6.75,6.15 7.59,5.88 9.5,7.17C10.29,6.95 11.15,6.84 12,6.84C12.85,6.84 13.71,6.95 14.5,7.17C16.41,5.88 17.25,6.15 17.25,6.15C17.8,7.5 17.45,8.54 17.35,8.79C18,9.5 18.38,10.39 18.38,11.5C18.38,15.32 16.04,16.16 13.81,16.41C14.17,16.72 14.5,17.33 14.5,18.26C14.5,19.6 14.5,20.68 14.5,21C14.5,21.27 14.66,21.59 15.17,21.5C19.14,20.16 22,16.42 22,12A10,10 0 0,0 12,2Z' /></svg>"); }

.md-typeset .magiclink-repository.magiclink-gitlab::before {
  -webkit-mask-image: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><path d='M3.16,10L12,21.5L2.32,14.3C2.05,14.09 1.94,13.75 2.04,13.44L3.16,10M6.11,3.17C6,2.83 5.5,2.83 5.37,3.17L3.16,10H8.32L6.11,3.17M8.32,10L12,21.5L15.68,10H8.32M21.96,13.44L20.84,10L12,21.5L21.68,14.3C21.95,14.09 22.06,13.75 21.96,13.44M18.63,3.17C18.5,2.83 18,2.83 17.89,3.17L15.68,10H20.84L18.63,3.17Z' /></svg>");
          mask-image: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><path d='M3.16,10L12,21.5L2.32,14.3C2.05,14.09 1.94,13.75 2.04,13.44L3.16,10M6.11,3.17C6,2.83 5.5,2.83 5.37,3.17L3.16,10H8.32L6.11,3.17M8.32,10L12,21.5L15.68,10H8.32M21.96,13.44L20.84,10L12,21.5L21.68,14.3C21.95,14.09 22.06,13.75 21.96,13.44M18.63,3.17C18.5,2.83 18,2.83 17.89,3.17L15.68,10H20.84L18.63,3.17Z' /></svg>"); }

.md-typeset .magiclink-repository.magiclink-bitbucket::before {
  -webkit-mask-image: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><path d='M21.43,2C21.79,2.07 22.03,2.42 22,2.82L21.12,8.7L19.27,21.4C19.2,21.75 18.95,22 18.63,22H5.37C5.05,22 4.8,21.75 4.73,21.4L2.88,8.7L2,2.82C1.97,2.42 2.21,2.07 2.57,2H21.43M14.08,15.26L15.1,8.7H8.9L9.92,15.26H14.08Z' /></svg>");
          mask-image: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><path d='M21.43,2C21.79,2.07 22.03,2.42 22,2.82L21.12,8.7L19.27,21.4C19.2,21.75 18.95,22 18.63,22H5.37C5.05,22 4.8,21.75 4.73,21.4L2.88,8.7L2,2.82C1.97,2.42 2.21,2.07 2.57,2H21.43M14.08,15.26L15.1,8.7H8.9L9.92,15.26H14.08Z' /></svg>"); }
```

@gir-bot add T: bug, S: confirmed
@gir-bot lgtm

**Comment by Andre601** [comment] 2020-03-28 15:26
Thanks for the info and the css snippet.

**Comment by facelessuser** [comment] 2020-03-28 16:45
Okay, I have a fix coming that should be included in the 7.0 release on April 7

**Comment by facelessuser** [comment] 2020-03-28 21:42
I now remember why I don't shorten user and repos:

Because you can't always distinguish links `https://github.com/settings/billing` is not a repo `https://github.com/marketplace` is not a user. There are an unknown number of these. Since we don't actually connect to verify a user or a repo, having this on all the time is not a good idea.

**Comment by facelessuser** [comment] 2020-03-28 21:44
Apparently, I even say as much in the docs: https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/#repository-link-shortener.

So I am not going to patch this. This is a known behavior that is documented.

**Comment by facelessuser** [comment] 2020-03-28 21:45
@gir-bot remove S: confirmed
@gir-bot add S: wontfix

**Comment by facelessuser** [comment] 2020-03-29 16:50
Maybe we can make this optional, and if you need to link one of GitHub's links that conflicts, you can provide an exclusion list.

**Comment by facelessuser** [comment] 2020-03-29 22:19
So, I've decided I will add this support, it will come with a new option though called `shortener_user_exclude`. This will be used to exclude certain paths, for instance `https://github.com/support`. We don't want that to be recognized as a user. Nor do we want anything following it to be considered for a repository. We will include a list of defaults, but users can override it with others or pull request to make it official.

@gir-bot remove S: wontfix
@gir-bot add T: feature

**Closed** 2020-03-30 01:22 UTC
Labels: T: feature
