### ISSUE TITLE
Insert jupyter notebooks inside snippets

### ISSUE THREAD

**Issue by HugoMVale** [facelessuser/pymdown-extensions#2197] opened 2023-10-06 19:12 UTC
### Description

Snippets allow one to insert text in a md file. [mkdocs-jupyter](https://github.com/danielfrg/mkdocs-jupyter) makes it possible to render jupyter notebooks as documentation pages. It would quite nice to be able to combine these 2 features, so that one could insert a "short" jupyter notebook somewhere inside a documentation page written in md.  

### Benefits

I believe this could be be quite helpful when writing API docs. One could then include a short jupyter notebook with examples at the bottom of the page.  There are other methods (e.g., markdown-exec) to include code in pages, but they are not as flexible, dynamic and rich as jupyter notebooks.

**Comment by facelessuser** [comment] 2023-10-06 19:43
I'm not sure I understand. You can insert anything with Snippets. You will have to provide me an example.

**Comment by HugoMVale** [comment] 2023-10-06 19:53
Thanks for taking the time to reply. Yes, one can insert anything. But if we insert a jupyter notebook file, it will be inserted as "raw" text, rather than being rendered as jupyter notebook.

You can see a jupyter notebook here: https://github.com/HugoMVale/polykin/blob/main/docs/tutorials/coefficients.ipynb

You can see how it is rendered as an mkdocs page (thanks to mkdocs-jupyter) here: https://hugomvale.github.io/polykin/tutorials/coefficients/
 
We would need to something that recognizes the file format in the Snippet and calls mkdocs-jupyter to do the conversion on the fly.

**Comment by facelessuser** [comment] 2023-10-09 16:13
It is difficult for me to answer your question without you specifically providing me a minimal, reproducible example. I'm not sure what you specified, how you've configured things, etc.

**Comment by facelessuser** [comment] 2023-10-14 14:54
As no minimal, reproducible examples have been provided, I am closing this issue. Feel free to reopen if you get around to providing one.

**Closed by facelessuser** 2023-10-14 14:54 UTC
Labels: T: feature, S: more-info-needed, S: triage

**Comment by HugoMVale** [comment] 2023-10-14 15:29
> As no minimal, reproducible examples have been provided, I am closing this issue. Feel free to reopen if you get around to providing one.

Hello. Sorry for taking to long to work on this. A reproducible example can be found here:
* https://github.com/HugoMVale/polykin/blob/main/docs/reference/physprops/vapor_pressure.md

The outcome can be viewed here:
* https://hugomvale.github.io/polykin/reference/physprops/vapor_pressure/#example-to-check-snippetjupyter

**Comment by facelessuser** [comment] 2023-10-14 16:02
@HugoMVale 
I need a minimal example that is just demonstrating this issue. All non-essential plugins, content, etc. should be removed: https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/?h=minimal#minimal-reproduction.

I have no time to debug your entire documentation project. My goal is to make sure Snippets is not introducing undesirable effects. Ideally, your minimal example should be able to demonstrate without using snippets that things are working and when inserting with snippets it is failing. If it is failing in both cases, Snippets is not responsible.

**Comment by facelessuser** [comment] 2023-10-14 16:02
Please provide a zip with your minimal example.

**Comment by HugoMVale** [comment] 2023-10-14 18:26
There you go. I hope this does it. Thanks in advance.

[test-snippets-jupyter.zip](https://github.com/facelessuser/pymdown-extensions/files/12907423/test-snippets-jupyter.zip)

**Comment by facelessuser** [comment] 2023-10-14 19:29
Okay, here's the problem. The Jupyter and Snippets plugins don't work the way you think/hope they do.  Snippets takes a file and inserts it into another file before the Markdown parser does anything to a file. So if you can't copy and paste Jupyter content in the middle of a Markdown file and get the Jupyter plugin to recognize that content, then that is an issue for the Jupyter plugin to sort out, if they even want to support that.

What you want is for Snippets to point at some notebook file, but then insert the rendereded HTML form of that notebook file. Snippets has no knowledge of Jupyter, MkDocs, or any other plugin. It simply takes a file and inserts it into another file. It doesn't know that what you actually want is an HTML file that doesn't even exist yet.

Basically, you've given me two examples that are _not_ testing the same thing.

1. [The working example] You are linking to a notebook, which works, but it links to an already rendered notebook, under `site/notebook/index.html` which the Jupyter notebook plugin has rendered and linked to within the final documentation output.
2. [Snippets] You are pointing it at a raw notebook file and inserting that raw notebook data into a markdown file, so it is then parsed with raw Markdown content. And since the Jupyter plugin doesn't scan a normal Markdown file.

I know this is not a Snippets issue because if I remove Snippets and just paste the notebook content into the Markdown file, it still doesn't work. Either Jupyter doesn't support this, or you need to read up on how Jupyter can be configured to do this.

If you want Jupyter to scan a Markdown file for Jupyter content, you need to see if there is a format it already supports that you are not using, or request such support. They may have no interest in doing so, but there is currently nothing for me to do here for Snippets.

**Comment by HugoMVale** [comment] 2023-10-14 19:55
First of all, thank you for having a look at this matter. Your reply somehow implies that I've opened this thread because of an _issue_. That is not the case. This thread was created for a potential _feature_. If you read again my first two posts, this might now become more obvious.

I've contacted you the same way that I have contacted the author of mkdocs-jupyter [#173](https://github.com/danielfrg/mkdocs-jupyter/issues/173), in the hope that a bridge/solution could be built starting from one of the two sides. It's alright, if that is not possible. 

Thanks again for your time.
