### ISSUE TITLE
Superfences issue with Mermaid

### ISSUE THREAD

**Issue by bnice5000** [facelessuser/pymdown-extensions#1013] opened 2020-07-07 11:38 UTC
I am setting up superfences with mermaid in pelican. When I use the `superfences.fence_div_format`, it surrounds it with a div but it converts all the `>` and `<` into `&lt` and `&gt;`. Because of that mermaid cannot make heads or tail of the configuration. I feel like I followed the directions but I might be missing something. Any help would be greatly appreciated.

Currently my configuration is as follows:

```python
import pymdownx.superfences as superfences

MARKDOWN = {
    'extension_configs': {
        'markdown.extensions.codehilite': {'css_class': 'highlight'},
        'markdown.extensions.smarty': {},
        'markdown.extensions.meta': {},
        'markdown.extensions.admonition': {},
        'markdown.extensions.toc': {},
        'pymdownx.extra': {
            "pymdownx.superfences": {
                "custom_fences": [
                    # {'name': 'flow', 'class': 'uml-flowchart'},
                    # {'name': 'sequence', 'class': 'uml-sequence-diagram'},
                    {'name': 'mermaid', 'class': 'mermaid', 'format': superfences.fence_div_format}, 
                ]}
        },
        'pymdownx.tilde': {},
        'pymdownx.tasklist': {},
        'pymdownx.smartsymbols': {},
    },
}
```

When I input the following:
````markdown
```mermaid
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br>prevail!
    John-->>Alice: Great!
    John->>Bob: How about you?
    Bob-->>John: Jolly good!
```
````
It returns the following output:

```html5
div class="mermaid">sequenceDiagram
    participant Alice
    participant Bob
    Alice-&gt;&gt;John: Hello John, how are you?
    loop Healthcheck
        John-&gt;&gt;John: Fight against hypochondria
    end
    Note right of John: Rational thoughts &lt;br/&gt;prevail!
    John—&gt;&gt;Alice: Great!
    John-&gt;&gt;Bob: How about you?
    Bob—&gt;&gt;John: Jolly good!</div>
```

**Comment by facelessuser** [comment] 2020-07-07 12:56
1. This is by design as content in tags that contain both `<` and `>` can cause HTML issues because usage of `<` and `>` can cause the browser to see HTML tags that are not there. All of the examples in our documentation that show mermaid use are generated with `<` and `>` being escaped, and it all works fine.

2. The only time you would need escaping to not be done is if you were trying to send through HTML tags as content to Mermaid, in that case, you may want to not escape specific `<` and `>`. You can create a custom fence if you absolutely need to do so: https://github.com/facelessuser/pymdown-extensions/issues/964.

3. While SuperFences provides a demo of what can be done and uses Mermaid in that demo, SuperFences does not offer specific support for Mermaid beyond the examples it provides.

@gir-bot remove S: triage
@gir-bot add S: wontfix

**Comment by bnice5000** [comment] 2020-07-07 14:43
I get point 1, the examples are not escaped, because I copied the sample from the website. It might be worth mentioning in the documentation that they need to be escaped, or maybe just actually escape them in the documentation.

Point 2 make scense and I will look into whether it is easier to escape the items or build the custom fence.

While I get where you are going with point 3, it is not super helpful, as I literally used _your copy and paste, feature from your documentation, on your website,_ to copy the example. I was not asking for specific mermaid help. I was just trying to make _your_ example work.

**Comment by bnice5000** [comment] 2020-07-07 15:12
Just in case someone is having the same issue I am. The documentation will not work with superfences and Mermaid. Here is the code I used to actually make mermaid work. It requires creating your own superfence formatter. With this formatter Mermaid will work perfectly. 

```python

def mermaid_fence_div_format(source, language, css_class, options, md, classes=None, id_value='', **kwargs):
    """Format source as div."""

    if id_value:
        id_value = ' id="{}"'.format(id_value)
    classes = css_class if classes is None else ' '.join(classes + [css_class])

    return '<pre><div{0} class="{1}">{2}</div></pre>'.format(id_value, classes, source)

```

**Comment by facelessuser** [comment] 2020-07-07 15:24
> While I get where you are going with point 3, it is not super helpful, as I literally used your copy and paste, feature from your documentation, on your website, to copy the example. I was not asking for specific mermaid help. I was just trying to make your example work.

I understand. I've also answered your question about `<` and `>`.  If you have a specific question about what I have in the docs, I am more than happy to clarify, and even update the docs to be more clear in that regard.

When dealing with questions about Mermaid though, I like to also emphasize that specifics regarding Mermaid features and behaviors are not supported here. I linked an issue where a user specifically wanted to not escape `<` and `>` because they wanted to pass through HTML elements. This was related, so I gave the related link and emphasis that if you desire something beyond what is provided by default, it may require a little research on your part. I am just being upfront and honest to steer the questions in a direction in which I am likely to answer them.

So, just to clarify, your original question was:

> It returns the following output:
>
> ```<div class="mermaid">sequenceDiagram
>         participant Alice
>         participant Bob
>         Alice-&gt;&gt;John: Hello John, how are you?
>         loop Healthcheck
>             John-&gt;&gt;John: Fight against hypochondria
>         end
>         Note right of John: Rational thoughts &lt;br/&gt;prevail!
>         John—&gt;&gt;Alice: Great!
>         John-&gt;&gt;Bob: How about you?
>         Bob—&gt;&gt;John: Jolly good!</div>
> ```

This is what I would expect. You then have to add and configure Mermaid accordingly and it should handle it. I don't see how you are using Mermaid, nor how you are configuring it. From a SuperFences perspective, the output is correct and there is nothing more to do there.

If you are seemingly configuring Mermaid correctly, and it isn't being recognized (which I would have to understand what you are doing first), then maybe I could add some more info if what is provided in the docs is not sufficient.

If you have a specific question about what I have in the docs, I am more than happy to clarify, and even update the docs to be more clear in that regard, but outside of that, I probably won't comment further.

**Comment by bnice5000** [comment] 2020-07-07 16:07
I am using Mermaid 8.5.2. Mermaid does not seem to support escaped `>` and `<` symbols in the latest release. If you use the following code in [their live editor](https://mermaid-js.github.io/mermaid-live-editor/), it generates an error.

```
sequenceDiagram
    participant Alice
    participant Bob
    Alice-&gt;&gt;John: Hello John, how are you?
    loop Healthcheck
        John-&gt;&gt;John: Fight against hypochondria
    end
    Note right of John: Rational thoughts &lt;br/&gt;prevail!
    John—&gt;&gt;Alice: Great!
    John-&gt;&gt;Bob: How about you?
    Bob—&gt;&gt;John: Jolly good!
```
Maybe with an older version of Mermaid this works?

The code modification I have posted above to the formater makes it work in my website. My site is generated using pelican.

**Comment by facelessuser** [comment] 2020-07-07 16:46
> I am using Mermaid 8.5.2. Mermaid does not seem to support escaped > and < symbols in the latest release. If you use the following code in their live editor, it generates an error.

How they are processing the input is different than how HTML content gets processed. I'm betting they escape the `&` causing a double escape. You can't really sue that as a good reference as I'm betting there is some formatting happening to your input.

---

So, just to illustrate that there is absolutely nothing wrong.

I am using the same configuration in the doc's example:

Ignore the format of the config as it is for MkDocs, but pay attention to the fact that I am using the div format in this example (I usually use something different):

```yml
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
```

Markdown source:

<img width="217" alt="Screenshot 2020-07-07 10 30 27" src="https://user-images.githubusercontent.com/1055125/86813564-909d7e00-c03d-11ea-9533-612e39afe62a.png">

My mermaid configuration (ignore the fact that I don't use a theme, I use some custom CSS, but that is irrelevant in this example). Just an FYI, I've also tested it without the config, and it still works, but the mermaid source must still be included.

```html
<script src="https://unpkg.com/mermaid@8.5.2/dist/mermaid.min.js"></script>
<script>
  var config = {
  	startOnLoad: true,
    theme: null,
    flowchart: {
      htmlLabels: false
    },
    sequence: {
      useMaxWidth: false
    },
    class: {
      textHeight: 16,
      dividerMargin: 16
    }
  };
  mermaid.initialize(config);
</script>
```

Proper Mermaid render in the documentation with browser dev tools showing that I am using the exact version you specified:

<img width="1056" alt="Screenshot 2020-07-07 10 31 28" src="https://user-images.githubusercontent.com/1055125/86813866-e5d98f80-c03d-11ea-9732-44001b846811.png">

This is the output source:

```html
<div class="mermaid">graph TB

    c1--&gt;a2
    subgraph one
    a1--&gt;a2
    end
    subgraph two
    b1--&gt;b2
    end
    subgraph three
    c1--&gt;c2
    end</div>
```

---

I hope you can see why I don't like to offer Mermaid support directly. I've already spent a lot of time re-illustrating what is already in the docs.

**Comment by facelessuser** [comment] 2020-07-07 16:47
One note, HTML minifiers will potentially remove newlines in your mermaid divs and break the library's ability to process the content. I had to disable my docs minifier to get this to work.

**Comment by facelessuser** [comment] 2020-07-08 13:19
I think this question has been sufficiently answered, and as there is currently no action item to follow up on, I'm closing the issue.

**Comment by facelessuser** [comment] 2020-07-09 12:51
I'm assuming this question was answered, so closing. If you have more questions, feel free to ask on discord, or create a new issue with the specific question.

**Closed by facelessuser** 2020-07-09 12:51 UTC
Labels: S: wontfix
