### ISSUE TITLE
[Bug][SuperFences] Trimming empty <span>

### ISSUE THREAD

**Issue by Kristinita** [facelessuser/pymdown-extensions#214] opened 2018-01-07 13:40 UTC
### 1. Summary

**If** I use SuperFences, empty `<span>` add to my code.

[**Tidy**](http://www.html-tidy.org/) output:

```shell
D:\Kristinita>tidy SashaExample.html
line 80 column 39 - Warning: trimming empty <span>
```

#### 2.1. Environment

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Python 3.6.4,
+ Pelican (site generator) 3.7.1,
+ Python Markdown 2.6.11,
+ pymdown-extensions 4.7,
+ Pygments 2.2.0.

#### 2.2. Configuration

Part of my `pelicanconf.py`:

```python
MARKDOWN = {
    'extension_configs': {

        'pymdownx.inlinehilite': {'css_class': 'SashaInlineHighlight',
                                  'style_plain_text': True,
                                  # [DEPRECATED] in 3.0 pymdown-extensions version
                                  # 'use_codehilite_settings': True,
                                  },
        'pymdownx.superfences': {'css_class': 'SashaBlockHighlight'}
}
```

My example `SashaExample.md` file (I replace backticks to single quotes):

```markdown
'''python
from Sasha import Goddess
'''
```

### 3. Steps to reproduce

I run `pelican content -s pelicanconf.py` command.

### 4. Expected behavior

```html
<div class="SashaBlockHighlight"><pre><span class="kn">from</span> <span class="nn">Sasha</span> <span class="kn">import</span> <span class="n">Goddess</span></pre></div>
```

### 5. Actual behavior

Unexpected `<span></span>` after class name.

```html
<div class="SashaBlockHighlight"><pre><span></span><span class="kn">from</span> <span class="nn">Sasha</span> <span class="kn">import</span> <span class="n">Goddess</span></pre></div>
```

**If** I remove`<span></span>`, nothing will change. If trimming span needs, then why?

Thanks.

**Comment by facelessuser** [comment] 2018-01-07 16:24
This is not a bug, but something that Pygments specifically does on purpose; please reference Pygments issue which resulted in this "feature": https://bitbucket.org/birkenfeld/pygments-main/issues/1111/an-empty-line-at-first-has-been-ignored.  Their change is here: https://bitbucket.org/birkenfeld/pygments-main/commits/164574c13533.

Anyways, SuperFences does not do anything to cause this as it relies on Pygments to do the color highlighting and formatting of the code.

**Comment by facelessuser** [comment] 2018-01-08 01:13
Closing this as there is no actionable item for pymdown-extensions.

**Closed by facelessuser** 2018-01-08 01:13 UTC
Labels: Works as Expected

**Comment by Kristinita** [comment] 2018-01-21 04:30
@facelessuser, for example, I check **<https://facelessuser.github.io/pymdown-extensions/>** page.

```shell
D:\Киролайна\Тестовые файлы>tidy -e facelessuser.html
line 847 column 1 - Warning: inserting implicit <p>
line 875 column 61 - Warning: <input> attribute "checked/" lacks value
line 876 column 61 - Warning: <input> attribute "checked/" lacks value
line 877 column 61 - Warning: <input> attribute "disabled/" lacks value
line 112 column 5 - Warning: <form> anchor "search" already defined
line 75 column 5 - Warning: trimming empty <label>
line 88 column 9 - Warning: trimming empty <label>
line 107 column 13 - Warning: trimming empty <label>
line 110 column 3 - Warning: trimming empty <label>
line 114 column 7 - Warning: trimming empty <label>
line 762 column 30 - Warning: trimming empty <span>
line 841 column 1 - Warning: trimming empty <p>
line 847 column 1 - Warning: trimming empty <p>
line 875 column 102 - Warning: trimming empty <span>
line 876 column 102 - Warning: trimming empty <span>
line 877 column 94 - Warning: trimming empty <span>
line 941 column 15 - Warning: trimming empty <i>
line 69 column 11 - Warning: <svg> proprietary attribute "xmlns"
line 69 column 11 - Warning: <svg> proprietary attribute "width"
line 69 column 11 - Warning: <svg> proprietary attribute "height"
line 69 column 11 - Warning: <svg> proprietary attribute "viewbox"
line 69 column 11 - Warning: <svg> proprietary attribute "id"
line 113 column 7 - Warning: <input> proprietary attribute "autocapitalize"
line 113 column 7 - Warning: <input> proprietary attribute "autocorrect"
Info: Document content looks like HTML5
Tidy found 24 warnings and 0 errors!
```

`Trimming empty` warnings in your HTML. How do you plain fix them?

I use Grunt for build my site, but Grunt Tidy plugin, possibly, [**no longer maintained**](https://github.com/gavinballard/grunt-htmltidy/issues/6). I need to search alternative solutions.

Thanks.

**Comment by facelessuser** [comment] 2018-01-22 02:07
I guess I don't understand the question.  What is `Trimming empty`?  Is this just warnings from tidy complaining about empty tags?  If so, I still don't see the issue.  I'm all for style guides and linters, but often when you are linting auto-generated files, you are going to have things you can't control.

 If there are some specific suggestions you have, I'm open.  If this is only relating to the empty spans in code tags, that is controlled by Pygments, so you'll have to take that upstream as I don't have control over that.

In general there appears to be no real problems.  It seems to complain about `checked` not having a value, but that is commonly how that attribute is used.  Empty tags are harmless and are at times used on purpose.  For instance, empty `<i>` tags are often used for font icons.  CSS is applied to target these tags with classes and insert the icon via `:before`.

I look at most of these generated "warnings" as suggestions, and many of them I would simply ignore.  But if you have a specific case, that I have control over, and there isn't a reason it has to be like included like it is, I'd be happy to make a modification.
