### ISSUE TITLE
Arithmatex does not preserve math equations in code block

### ISSUE THREAD

**Issue by prettykingking** [facelessuser/pymdown-extensions#1047] opened 2020-08-05 09:57 UTC
It's very often to write pseudo-code as plain code block, often with math symbols. So the Arithmatex should preserve math equations within plain code block too. It would be great. 😄 

**Example Pseudo-Code**
```
T = []
For each time slot $i$
    For each topic t in T
        If $e_i^I$ > $\beta_m$ Then
            ...
       Else
            ...
       End If
   End For
End For
...
```

**Comment by facelessuser** [comment] 2020-08-05 13:16
I'm not sure what you are requesting. I'm assuming the content above is in a code block?

````
```
T = []
For each time slot $i$
    For each topic t in T
        If $e_i^I$ > $\beta_m$ Then
            ...
       Else
            ...
       End If
   End For
End For
...
```
````

If so Code blocks are meant to preserve **any** content from **any** Markdown formatting which would include code blocks. That is by design. If you would like some hybrid version of Code and math, you would have to provide your own custom fence, and potentially have to run that content through some of the other parser logic.

Code blocks don't any other content within them (math or otherwise). It also wouldn't surprise me if match libraries like MathJax ignore code blocks by default.

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by prettykingking** [comment] 2020-08-06 02:00
I am sorry for that I didn't make myself clear, but you understand very well.

I was expecting math equations only  in plain code block could get preserved, not programming language specific code block.

Plain code block
````
```
T = []
For each time slot $i$
    For each topic t in T
        If $e_i^I$ > $\beta_m$ Then
            ...
        Else
            ...
        End If
   End For
End For
...
```
````

Language specific code block
```` python
``` python
print('I love Python')
```
````

You are right, Code block does not preserver any formatting by design. Maybe I have to deal with parse logic.

Thanks for your idea.

**Comment by facelessuser** [comment] 2020-08-06 05:51
As things are working as expected, I will close this issue.

**Closed by facelessuser** 2020-08-06 05:51 UTC
Labels: T: support
