### ISSUE TITLE
Emoji causes mkdocs crash/build failure

### ISSUE THREAD

**Issue by Stanzilla** [facelessuser/pymdown-extensions#768] opened 2019-12-19 12:54 UTC
I used :tada: in a page today and it crashed it

```
7:49:55 AM: ERROR   -  Error reading page 'news/events/game_jam.md': 'str' object is not callable
7:49:55 AM: Traceback (most recent call last):
7:49:55 AM:   File "/opt/buildhome/python3.7/bin/mkdocs", line 8, in <module>
7:49:55 AM:     sys.exit(cli())
7:49:55 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
7:49:55 AM:     return self.main(*args, **kwargs)
7:49:55 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
7:49:55 AM:     rv = self.invoke(ctx)
7:49:55 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
7:49:55 AM:     return _process_result(sub_ctx.command.invoke(sub_ctx))
7:49:55 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
7:49:55 AM:     return ctx.invoke(self.callback, **ctx.params)
7:49:55 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
7:49:55 AM:     return callback(*args, **kwargs)
7:49:55 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/__main__.py", line 163, in build_command
7:49:55 AM:     ), dirty=not clean)
7:49:55 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
7:49:55 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/commands/build.py", line 274, in build
7:49:55 AM:     _populate_page(file.page, config, files, dirty)
7:49:55 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/commands/build.py", line 177, in _populate_page
7:49:55 AM:     page.render(config, files)
7:49:55 AM: Shutting down logging, 30 messages pending
```

 my markdown_extensions page looks like this:

```yaml
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
```

**Comment by facelessuser** [comment] 2019-12-19 15:45
There seems to be nothing wrong with output. The HTML looks valid and correct:

```py
import markdown
from pymdownx import emoji

extensions = ['pymdownx.emoji']
extension_configs = {
    "pymdownx.emoji": {
        "emoji_index": emoji.twemoji,
        "emoji_generator": emoji.to_svg
    }
}

print(markdown.Markdown(extensions=extensions, extension_configs=extension_configs).convert(':tada:'))
```

Output:

```
<p><img alt="🎉" class="twemoji" src="https://twemoji.maxcdn.com/v/latest/svg/1f389.svg" title=":tada:" /></p>
```

Other users of MkDocs have no issue exporting that emoji either: https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#emoji

I also use emoji in this projects documentation (which is rendered with MkDocs) with no issues at all.

I see no evidence that this is a pymdown-extensions issue. In order for me to look into this further, I would need:

1. A [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example).
2. Evidence that this extension bundle is somehow contributing the issue.
3. Specific version of this extension that is causing failure. 

As things stand now, I have neither of these, and too much evidence and examples supporting that there is no issue with these extensions.

@gir-bot remove S: triage
@gir-bot add S: more-info-needed

**Comment by Stanzilla** [comment] 2019-12-19 16:18
Interesting, so it's not one specific emoji, it's actually *any* emoji. And if you use an invalid identifier, like :test: it won't crash either.

**Comment by facelessuser** [comment] 2019-12-19 16:31
> Interesting, so it's not one specific emoji, it's actually any emoji. And if you use an invalid identifier, like :test: it won't crash either.

Again, this is not reproducible for me at all. I'm using the latest mkdocs, mkdocs-material, and pymdown-extensions. I get no crash. This is rendered locally just minutes ago:

![emoji](https://user-images.githubusercontent.com/1055125/71190590-1a246480-2242-11ea-9cde-85621faa43b9.png)

You are going to have to narrow down what is different on your system, because right now everything is pointing to a user environment issue. That, or improper configuration somehow.

**Comment by facelessuser** [comment] 2019-12-19 16:32
@gir-bot add T: support

**Comment by facelessuser** [comment] 2019-12-19 17:07
```
7:49:55 AM: ERROR   -  Error reading page 'news/events/game_jam.md': 'str' object is not callable
```

This line suggests that something outside of emoji is causing your issue. It sounds like a string is getting called as a function. Also the traceback doesn't indicate an error in pymdown-extensions, but in mkdocs itself. 

I don't know what else you have in your mkdocs config: plugins, other configurations, etc., but it appears that there is something external to pymdown-extensions causing you issues. While it may be true that an emoji being present breaks your documentation, it sounds like something else that is parsing the document is to plain. I'd double check any mkdocs plugins, configurations, or anything else  you can possibly think of.

You are more than welcome to fork this repository and run mkdocs as a control to compare. This projects compiles its documentation without issues.

As I can see no actionable item for me to take on, I will close this issue. If you are able to narrow down some information that proves otherwise, we can reopen, but as things stand now, I am fairly confident this is a user environment/configuration issue, or some other 3rd party library issue.

**Closed by facelessuser** 2019-12-19 17:07 UTC
Labels: S: more-info-needed, T: support

**Comment by Stanzilla** [comment] 2019-12-19 17:11
Thank you!
