### ISSUE TITLE
Support attributes for content tabs

### ISSUE THREAD

**Issue by zhimsel** [facelessuser/pymdown-extensions#1766] opened 2022-07-28 18:22 UTC
### Description

As described in [this feature request for `mkdocs-material`](https://github.com/squidfunk/mkdocs-material/issues/4175), I'd like to request that tabbed content (`=== "Some title"`) have support added for arbitrary attributes. 

> However, we might be able to add support for a `no-link` attribute (or similar) on content tabs, which would allow us to disable linking for a specific tab group. This could be accompanied by a `link` attribute, which would allow to opt a specific tab group into linking without making all content tabs linked.
> 
> The problem is that content tabs currently don't support adding attributes ([Attribute Lists](https://python-markdown.github.io/extensions/attr_list/)) so this would need to be implemented first. You may follow up with [Python Markdown Extensions](https://github.com/facelessuser/pymdown-extensions), which implemented content tabs if the functionality described works for you. As soon as this is implemented we can add support in Material for MkDocs.

### Benefits

This would enable the behavior of the tabs to be modified on a per-tab basis. A specific example is given in https://github.com/squidfunk/mkdocs-material/issues/4175

### Solution Idea

The interface could look something like this:

```markdown
=== "Title for a tab" key1=value1

Foo

=== "Title for another tab"  key2=value2

Bar
```

**Comment by facelessuser** [comment] 2022-07-28 19:45
This is actually a duplicate of #1194 as the functionality would be identical. If I were to do this, I'd do it via the `attr_list` extension, or better put, allow the Tabbed extension to support `attr_list`.

> Why haven't we already added support?

Well, this is because, originally, we created the Details extension as a copy paste of Admonitions. We duplicated the exact syntax and behavior, but applied it to Details instead of admonitions. This applies to Tabbed as well because we then duplicated that syntax again for Tabbed. This is mainly because Python Markdown best supports contains via indentation, fencing is very difficult and is why SuperFences is so complicated.

This is important to know because Admonitions uses a very naive syntax where the title is parsed such that the only rules is that it must start with a double quote and end with the same double quote, and this is the important part,  _at the end of the line_.

So, this awkward title will parse fine:

```
"this has quotes in the "middle" but will still parse fine"
```

But this won't:

```
"Title" anything after
```

> So, can't you just fix it?

Yes, I can, but I'll likely break other people's stuff. That awkward title earlier is perfectly valid. To do this correctly, I'd need to change the title syntax by either requiring escapes so we can parse the title in a sane way, or maybe doing something like fences that uses multiple quotes, and as long as the middle quotes don't match the count, they are allowed:

```
"""this has quotes in the "middle" but will still parse fine"""
```

Then we could safely do things like:

```
"""this has quotes in the "middle" but will still parse fine""" {key="whatever"}
```

I think I lean more towards something like above as I'd hate to double backslash escaping into this syntax. Like if you have to backslash escape a quote, but then Markdown content also allows escaping via backslash, it becomes less desirable. I'm open to suggestions though.

I guess there is still one more approach we could use that would be backwards compatible. I thought of it as I was typing this:

```
=== "title {key="value"}"
```

This would not apply to just the title, but the whole block. This would take title specific attributes out of the equation.

But, there is one last thing as this will create a disparity between our "Admonition-like" extensions and the Admonition extension itself. Pymdown containers would support this with Admonitions as the "odd man out". So we'd probably want to just maintain our own variant of Admonitions that also supports `attr_list` properties.

> So, let's just do something like that

Well, I might, it's something I've been toying with. I'd like to come up with some sort of accepted way in the official, Python Markdown Admonitions extension. I need to open up conversation there again as I'd hate to just fork that extension here, but if necessary, it wouldn't be the first time, that's how SuperFences happened.

> But, there may be an alternative...

One alternative, I think one that Python Markdown has been toying with, is maybe some generic container format that could be adopted to handle things like Admonitions, etc. Fenced code is difficult for the Python Markdown parser as fenced code can have multiple new lines in a row, and the Python Markdown parser kicks out of lists and such if it sees more than one newline in a row. But admonition content? That's just normal Markdown text (paragraphs, blockquotes, stuff that Python Markdown handles fine), and SuperFences already handles the code stuff. If I can get a generic container format going, we could eliminate all the these indentation specific container formats. People don't generally like having to do all the indenting. I've been considering looking into this as well. This may be an even better approach moving forward as it opens the possibilities for other containers.

Anyways, this is definitely on my list of things to explore as I feel this provides some needed value.

**Comment by squidfunk** [comment] 2022-07-30 10:57
I think this would allow for many more useful additions downstream in Material for MkDocs. Allowing to add attributes to details, tabs, and other elements would enable tagging of components to add or remove specific functionality. However, I understand that this is a long-short and needs some serious thinking given that it'll most certainly be a breaking change.

**Comment by facelessuser** [comment] 2022-07-30 12:36
I definitely see the benefit of this feature. I also wish I had recognized this title issue in the early days. At the time, I just wanted Details to match Admonitions in the way they worked, and the containerized approach also seem to make sense for tabs, but I think is solvable. Regardless of how I solve it, it may need to be under a feature flag, especially if it alters parsing behavior.

I'd like to try and open up a conversation again over at Python Markdown to see if we can brainstorm a way to allow attribute lists in Admonitions because I'd love to mirror what they do and not fork Admonitions, but that may or may not be unavoidable.

Regardless, I also plan to explore a new, unintended container form as well.

Overall, I think this issue and related ones will be my next big push in Pymdown Extensions.

**Comment by squidfunk** [comment] 2022-07-30 13:28
We can definitely add support behind a feature flag, as we did for content tabs. Depending on how different the implementation is, we might even keep support for the old generated HTML and/or syntax, as we did with content tabs until the next major release. If it's not feasible, we can do a major release.

> I'd like to try and open up a conversation again over at Python Markdown to see if we can brainstorm a way to allow attribute lists in Admonitions because I'd love to mirror what they do and not fork Admonitions, but that may or may not be unavoidable.

Always best to deduplicate efforts 😊

**Comment by facelessuser** [comment] 2022-08-03 13:06
Closing as a duplicate of #1194. Whatever resolution we end up having will be done under #1194.

**Closed by facelessuser** 2022-08-03 13:06 UTC
Labels: T: feature, S: triage
