### ISSUE TITLE
Resource leak in the Github extension

### ISSUE THREAD

**Issue by ghtyrant** [facelessuser/pymdown-extensions#15] opened 2016-08-11 23:06 UTC
I'm using Markdown and pymdown-extensions (`pymdownx.github`) to implement a live preview of what a user is typing. While testing that, I noticed speed problems occurring after typing for a while.
I'm keeping an instance of Markdown (`self.md = markdown.Markdown()`) in my class and run `self.md.convert(text)` every time the input text changes. The time it takes to convert the text, measured using time.clock() increases with every call. You could say that this is expected behaviour but it does so at a very high rate.

Out of curiosity, I compared my current method to using markdown.markdown(). This creates a new instance of Markdown on every call, so I expected it to be even slower.
But (Times in seconds, using time.clock()): 
```
markdown.convert(): 0.049039
markdown.markdown(): 0.002539
```
This was the time it took both methods to run on the same text input, after typing for a bit. Both use the same extensions (`pymdownx.github`). To verify my suspicion, I restarted my program and pasted the exact text back into it:
```
markdown.convert(): 0.003069
markdown.markdown(): 0.002402
```
This confirms, that the problem is not caused by the input text.

**I highly suspect one of the extensions in the github collection to fail at cleaning up its state correctly.**

**Versions**:
Python 3.4.4
Markdown 2.6.6
pymdown-extensions 1.1

**Comment by ghtyrant** [comment] 2016-08-12 13:29
I think I've found the culprit: `pymdownx.headeranchor`

```
Using an instance is 0.000439s slower than using markdown.markdown() (Text Length: 100016)
Round 0 finished.
Using an instance is 0.000470s faster than using markdown.markdown() (Text Length: 100024)
Using an instance is 0.001265s faster than using markdown.markdown() (Text Length: 100040)
Using an instance is 0.001713s slower than using markdown.markdown() (Text Length: 100048)
Using an instance is 0.001926s slower than using markdown.markdown() (Text Length: 100072)
(...)
Using an instance is 0.325306s slower than using markdown.markdown() (Text Length: 100728)
Using an instance is 0.341361s slower than using markdown.markdown() (Text Length: 100744)
(...)
```

This extension causes the runtime of md.convert() and markdown.markdown() to drift apart significantly.

Use the following code to reproduce:
```python
import time
import markdown
MARKDOWN_EXTENSIONS = [
    #"markdown.extensions.extra",
    #"markdown.extensions.admonition",
    #"markdown.extensions.codehilite",
    #"markdown.extensions.headerid",
    #"markdown.extensions.meta",
    #"markdown.extensions.nl2br",
    #"markdown.extensions.sane_lists",
    #"markdown.extensions.smarty",
    #"markdown.extensions.toc",
    #"markdown.extensions.wikilinks",
    #"pymdownx.github",
    #'markdown.extensions.tables',
    #'pymdownx.magiclink',
    #'pymdownx.betterem',
    #'pymdownx.tilde',
    #'pymdownx.githubemoji',
    #'pymdownx.tasklist',
    'pymdownx.headeranchor',
    #'pymdownx.superfences'
]

md = markdown.Markdown(extensions=MARKDOWN_EXTENSIONS)

def run_instance(md, text):
    return md.convert(text)

def run_fresh(text):
    return markdown.markdown(text, extensions=MARKDOWN_EXTENSIONS)

max_diff = 0
min_diff = 0
slower_count = 0
text = '# Hello World!\n\n' + 'f' * 100000
try:
    for x in range(0, 20000):
        start = time.clock()
        html = "test" + run_instance(md, text)
        delay = time.clock() - start

        start = time.clock()
        html = "test" + run_fresh(text)
        delay_fresh = time.clock() - start

        diff = delay - delay_fresh

        if diff > 0.0:
            slower_count += 1

        if diff > max_diff:
            max_diff = diff
            print("Using an instance is %.6fs slower than using markdown.markdown() (Text Length: %d)" % (diff, len(text)))

        if diff < min_diff:
            min_diff = diff
            print("Using an instance is %.6fs faster than using markdown.markdown() (Text Length: %d)" % (abs(diff), len(text)))

        if x % 500 == 0:
            print("Round %d finished." % x)

        text += '# Lorem' + '\n'
except KeyboardInterrupt:
    print("Instance was slower on %d rounds." % (slower_count))
```

**Comment by facelessuser** [comment] 2016-08-12 13:32
Thank you.  I'm currently out of town, but when I  get back, I will investigate further.

**Comment by facelessuser** [comment] 2016-08-12 13:45
Note to self.  As we don't really instantiate new stuff while running, maybe we are adding headeranchor multiple times: https://github.com/facelessuser/pymdown-extensions/blob/master/pymdownx/headeranchor.py#L165.  This would mean that something isn't working as expected with resets and instantiated extension classes.  If it isn't this, I'll have to dig in more.

**Comment by facelessuser** [comment] 2016-08-16 23:09
If I leave it running, I do see the there is a range of times, but I do see a slow creep in time with headeranchors.  I do not see headeranchors being added multiple times.  Unique Ids are reset on every run.  All regex patterns are are compiled once and only once.  I don't see anything obvious that would be leaking on my side.  I'll have to check the functions we import from existing Python Markdown extensions.

**Comment by facelessuser** [comment] 2016-08-17 00:52
The same issue exists with the `toc` extension.  `toc` is what `headeranchors` borrows some functions from via imports.  I imagine the issue is there.  With that said, I want to at least understand the issue, so I will dig further.

**Comment by facelessuser** [comment] 2016-08-17 02:41
Nevermind.  It looks like I am inflating the rawHtmlBlocks stash.

**Comment by facelessuser** [comment] 2016-08-17 03:07
Yeah, I was right.  `toc` is at fault too.  No one clears the rawHtmlBlocks stash.  At least the problem is now identified.

**Comment by facelessuser** [comment] 2016-08-17 04:58
Okay, this is **not** a bug.  This is apparently a usage error.

Try this:

```python
import time
import markdown
MARKDOWN_EXTENSIONS = [
    #"markdown.extensions.extra",
    #"markdown.extensions.admonition",
    #"markdown.extensions.codehilite",
    #"markdown.extensions.headerid",
    #"markdown.extensions.meta",
    #"markdown.extensions.nl2br",
    #"markdown.extensions.sane_lists",
    #"markdown.extensions.smarty",
    #"markdown.extensions.toc",
    #"markdown.extensions.wikilinks",
    #"pymdownx.github",
    #'markdown.extensions.tables',
    #'pymdownx.magiclink',
    #'pymdownx.betterem',
    #'pymdownx.tilde',
    #'pymdownx.githubemoji',
    #'pymdownx.tasklist',
    'pymdownx.headeranchor',
    #'pymdownx.superfences'
]

md = markdown.Markdown(extensions=MARKDOWN_EXTENSIONS)

def run_instance(md, text):
    md.reset()
    return md.convert(text)

def run_fresh(text):
    return markdown.markdown(text, extensions=MARKDOWN_EXTENSIONS)

max_diff = 0
min_diff = 0
slower_count = 0
text = '# Hello World!\n\n' + 'f' * 100000
try:
    for x in range(0, 20000):
        start = time.clock()
        html = "test" + run_instance(md, text)
        delay = time.clock() - start

        start = time.clock()
        html = "test" + run_fresh(text)
        delay_fresh = time.clock() - start

        diff = delay - delay_fresh

        if diff > 0.0:
            slower_count += 1

        if diff > max_diff:
            max_diff = diff
            print("Using an instance is %.6fs slower than using markdown.markdown() (Text Length: %d)" % (diff, len(text)))

        if diff < min_diff:
            min_diff = diff
            print("Using an instance is %.6fs faster than using markdown.markdown() (Text Length: %d)" % (abs(diff), len(text)))

        if x % 500 == 0:
            print("Round %d finished." % x)

        text += '# Lorem' + '\n'
except KeyboardInterrupt:
    print("Instance was slower on %d rounds." % (slower_count))
```

Notice all we are doing is calling `md.reset()` before convert.  The assumption was that all you needed to do was call convert, but we need to clean up between runs by calling reset.  When calling reset, I see nothing wrong.

**Comment by facelessuser** [comment] 2016-08-17 16:05
@ghtyrant , I am closing this issue as this appears to be a simple usage error.  If I have misidentified the issue, or there are still other issues, feel free to re-open the issue for further discussion.

**Closed by facelessuser** 2016-08-17 16:05 UTC
Labels: Works as Expected

**Comment by ghtyrant** [comment] 2016-08-17 17:31
Alright, thanks for clearing that up. I somehow missed that part in Markdown's documentation. IMHO, it's a weird design decision, but you are right, it's not a bug.

Thanks!

**Comment by facelessuser** [comment] 2016-08-17 17:34
Yeah, normally I would expect convert to clean up for you automatically.  I honestly don't even know if it is covered in their docs, but I found the reset method by looking at the code and saw that it did the clean up that wasn't getting done.

Anyways, it was a good exercise for me to run through as I am sure this question will come up again.

**Comment by ghtyrant** [comment] 2016-08-17 18:34
It does say so at the bottom of [this](https://pythonhosted.org/Markdown/reference.html#Markdown) page:

> Depending on which options and/or extensions are being used, the parser may need its state reset between each call to convert, otherwise performance can degrade drastically:

> ```
html1 = md.convert(text1)
md.reset()
html2 = md.convert(text2)
```
