### ISSUE TITLE
Arithmatex hang/slow render

### ISSUE THREAD

**Issue by heartbleeded** [facelessuser/pymdown-extensions#888] opened 2020-04-11 09:37 UTC
Hi,

I'm facing one Latex block which is slowly render by Arithmatex. It takes ~ 10 minutes to render.

Latex block:
```
text='''
$z^{[1]} = \begin{bmatrix}w^{[1]T}_1 \\ w^{[1]T}_2 \\ w^{[1]T}_3 \\ w^{[1]T}_4 \end{bmatrix} \begin{bmatrix}x_1 \\ x_2 \\ x_3 \end{bmatrix} + \begin{bmatrix}b^{[1]}_1 \\ b^{[1]}_2 \\ b^{[1]}_3 \\ b^{[1]}_4 \end{bmatrix}= \begin{bmatrix}w^{[1]T}_1 x + b^{[1]}_1 \\ w^{[1]T}_2 x + b^{[1]}_2\\ w^{[1]T}_3 x + b^{[1]}_3 \\ w^{[1]T}_4 x + b^{[1]}_4 \end{bmatrix} $
'''
html = markdown.markdown(text, extensions=['pymdownx.arithmatex'])
```

When Break pressed, it throws this backtrace:

```
 File "./markdown/core.py", line 388, in markdown
    return md.convert(text)
  File "./markdown/core.py", line 269, in convert
    newRoot = treeprocessor.run(root)
  File "./markdown/treeprocessors.py", line 370, in run
    self.__handleInline(text), child
  File "./markdown/treeprocessors.py", line 131, in __handleInline
    self.inlinePatterns[patternIndex], data, patternIndex, startIndex
  File "./markdown/treeprocessors.py", line 270, in __applyPattern
    for match in pattern.getCompiledRegExp().finditer(data, startIndex):
```

**Comment by facelessuser** [comment] 2020-04-11 13:21
The example given will not match proper (this is a note outside of the reported slowness):

1. In your example, you should probably be using a raw string `test=r'''`.
2. Also, Arithmatex also, when run in the default configuration you are using, should have the closing `$` with no spaces before it. This is the "smart" configuration that aims to avoid `$` when not using in a LaTeX manner.

Changing those two things fixes the hang.

---

As for the slowness, this appears to be the case when the pattern does not match, and I'm not yet sure why. I believe can do things in a much more efficient way, so I'll look into this.

@gir-bot remove S: triage
@gir-bot add T: bug, S: confirmed

**Comment by facelessuser** [comment] 2020-04-11 13:38
Looks like our issue is due to a regular expression typo: `[^\$]` should have been `[^\\$]`.

**Closed** 2020-04-11 15:05 UTC
Labels: S: confirmed, T: bug
