### ISSUE TITLE
Generalize SuperFences' special language blocks

### ISSUE THREAD

**Issue by bushnoh** [facelessuser/pymdown-extensions#60] opened 2017-03-01 17:20 UTC
It would be nice to have support for mermaid: [http://knsv.github.io/mermaid/](http://knsv.github.io/mermaid/).

Currently I have:
```
<div class="mermaid">
graph LR
    A[Square Rect] -- Link text --> B((Circle))
    A --> C(Round Rect)
    B --> D{Rhombus}
    C --> D
</div>

--8<-- "mermaid.md"
```

and:

```
cat docs/snippets/mermaid.md 
<script src="https://cdn.rawgit.com/knsv/mermaid/7.0.0/dist/mermaid.min.js"></script>
<link href="https://cdn.rawgit.com/knsv/mermaid/7.0.0/dist/mermaid.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript">
<script>mermaid.initialize({startOnLoad:true});</script>
</script>
```

So it would be minimal impact to transform:

````
```mermaid

```
````

into:

```
<div class="mermaid">

</div>
```

**Comment by facelessuser** [comment] 2017-03-01 17:54
Why would we need a separate class for mermaid?

If mermaid is an alternative flowchart/sequence diagram renderer, you don't **need** a special class, you would just point mermaid at the existing blocks instead using the suggested JavaScript libraries I note in the documentation.  SuperFences doesn't care what the actual content under flowchart or sequence-diagram is.  You should be able to target other classes other like `flowchart` and `sequence-diagram` (or whatever it is I assign to it by default)

Now, if the problem is that you want the flowcharts syntax under a div, that might be a feature request.  I currently chose a pre/code block because if the library doesn't load, I wanted it to look presentable, and the libraries I was using could be wrapped in such a way that I could process the blocks and manually feed the content through the libraries.  For mermaid, this manual feeding of the content might not be possible, so for a more simple approach, I could probably optionally output the content under a div and allow this to be more accessible by other libraries.

I don't imagine I will be adding a `mermaid` specific classes, but maybe I could allow outputting content under a div.  In the case of mermaid, you would just need to point it at the flowchart class and/or sequence diagram class.

Anyways, let me know your thoughts.

**Comment by facelessuser** [comment] 2017-03-01 17:57
I think you don't even need a div.  It **looks** like mermaid will allow you to leverage my existing examples in the docs and feed the content through as it looks like maybe you can feed in content directly to mermaid. Though I am not throwing out the idea of making this easier for people by allow output of a div.

**Comment by facelessuser** [comment] 2017-03-02 00:23
Something like this should work.  You would need to add the CSS to `mkdocs.yml` via `extra_css` as Python Markdown doesn't recognize `link` tags.

```js
<script src="https://cdn.rawgit.com/knsv/mermaid/7.0.0/dist/mermaid.min.js"></script>
<script type="text/javascript">
(function (document) {
    var convertUML = function(className, settings) {
        var charts = document.querySelectorAll("pre." + className),
            arr = [],
            i, j, maxItem, diagaram, text, curNode;

        // Is there a settings object?
        if (settings === void 0) {
            settings = {};
        }

        // Make sure we are dealing with an array
        for(i = 0, maxItem = charts.length; i < maxItem; i++) arr.push(charts[i]);

        // Find the UML source element and get the text
        for (i = 0, maxItem = arr.length; i < maxItem; i++) {
            childEl = arr[i].firstChild;
            parentEl = childEl.parentNode;
            text = "";
            for (j = 0; j < childEl.childNodes.length; j++) {
                curNode = childEl.childNodes[j];
                whitespace = /^\s*$/;
                if (curNode.nodeName === "#text" && !(whitespace.test(curNode.nodeValue))) {
                    text = curNode.nodeValue;
                    break;
                }
            }

            // Do UML conversion and replace source
            el = document.createElement('div');
            el.className = className;
            parentEl.parentNode.insertBefore(el, parentEl);
            parentEl.parentNode.removeChild(parentEl);
            mermaid.mermaidAPI.initialize(settings);
            console.log(mermaid.mermaidAPI.getConfig());
            var insertSvg = function(svgCode) {
                el.innerHTML = svgCode;
            };

            mermaid.mermaidAPI.render(className + '-' + i.toString(), text, insertSvg);
        }
    };

    function onReady(fn) {
        if (document.addEventListener) {
            document.addEventListener('DOMContentLoaded', fn);
        } else {
            document.attachEvent('onreadystatechange', function() {
                if (document.readyState === 'interactive')
                    fn();
            });
        }
    }

    onReady(function(){
        var config = {logLevel: 4, startOnLoad: false};
        convertUML('uml-flowchart', config);
        convertUML('uml-sequence-diagram', config);
    });
})(document);
</script>
```

Mermaid seems to log a bunch.  I tried setting `logLevel` to 4, but I think it ignores this, so maybe you know better as a Mermaid user.

**Comment by bushnoh** [comment] 2017-03-02 11:53
I understand your points about the `<pre><code>` switching and making another special case for mermaid. However this would depend on using the existing `uml-` classes.

How about generalising the tags that can be transformed with this pattern?
Something like the following is working for me:

```
diff --git a/usr/lib/python2.7/site-packages/pymdownx/superfences.py.bak b/usr/lib/python2.7/site-packages/pymdownx/superfences.py
index 9e21b95..ed30a5f 100644
--- a/usr/lib/python2.7/site-packages/pymdownx/superfences.py.bak
+++ b/usr/lib/python2.7/site-packages/pymdownx/superfences.py
@@ -145,6 +145,7 @@ class SuperFencesCodeExtension(Extension):
             'nested': [True, "Use nested fences - Default: True"],
             'uml_flow': [True, "Enable flowcharts - Default: True"],
             'uml_sequence': [True, "Enable sequence diagrams - Default: True"],
+            'lang_to_class': [{}, "Custom language to class map - Default: {}"],
             'highlight_code': [True, "Highlight code - Default: True"],
             'use_codehilite_settings': [
                 True,
@@ -200,6 +201,13 @@ class SuperFencesCodeExtension(Extension):
                 "sequence", "sequence",
                 lambda s, l, c="uml-sequence-diagram": uml_format(s, l, c)
             )
+        
+        lang_to_class = config.get("lang_to_class", {})
+        for k,v in lang_to_class.iteritems():
+            self.extend_super_fences(
+                k, k,
+                lambda s, l, c=v: uml_format(s, l, c)
+            )
 
         if not config.get('nested'):
             warnings.warn(
```

And then having this mapping kept in the config document:
```
    - pymdownx.superfences:
          lang_to_class:
              mermaid: mermaid-uml
```

Then the javascript snippet would be able to target any classes the user wished?

What do you think?

**Comment by facelessuser** [comment] 2017-03-02 14:03
Implementation isn't a problem, what I'm looking for is justification. Why are the existing classes not sufficient?  I personally understand the desire to use a div more than I do the need to customize the language name.  Can you explain why you think it is necessary to allow a mermaid language name?

**Comment by bushnoh** [comment] 2017-03-02 15:30
Hi, I know implementation isn't a problem, I was just using it to demonstrate what I was suggesting.

The current classes probably are sufficient, however it would be impossible to use both the mermaid library and flow or sequence library at the same time. Also, the same issue would be there if you wanted to target any future library without reusing the the `uml-sequence-diagram` or `uml-flow-diagram` classes. It would give generic future support for custom language handling, and superfences seems like a natural place to have this.

However, I can completely understand if you don't think this belongs here in the library. I don't think the question is:
> Can you explain why you think it is necessary to allow a mermaid language name?

But more along the lines of:
> Does a mermaid language (or generic language) belong in this library?
This question I can't answer.

**Comment by facelessuser** [comment] 2017-03-02 15:42
Hmm.  If the idea is to extend SuperFences to beyond UML, that makes sense.  If I do this, it may make sense to redesign the settings for this.  I would kill off the flow chart and sequence diagram boolean, and instead just allow people to feed in a generic list of language names.  To disable a language, you'd just remove the language name from the list.

While I'm doubtful mermaid would be used along side the other UML libraries (as they appear to do the same thing, but maybe I don't know enough about mermaid), I can see there being non UML libraries that may require similar logic.  So in that case, I can see how a generic interface may be desired.

Okay, let me think about this.  I can see the benefit. Let me think how I want the interface to look.

**Comment by facelessuser** [comment] 2017-04-02 20:11
Work is almost done on this.  Moving forward, custom fences will be generalized.  You will be able to feed in a list of custom fences with the following as the default.

```py
[
    {'name': 'flow', 'class': 'uml-flowchart', 'format': superfences.fence_code_format},
    {'name': 'sequence', 'class': 'uml-sequence-diagram', 'format': superfences.fence_code_format}
]
```

You will specify the fence langauge name, the class to apply to the HTML element that is output, and the format function that outputs the HTML.  The format function will take the source, fence name, and HTML class.  Two format functions will be provided with SuperFences: `fence_code_format` which will wrap the source in pre/code blocks, and `fence_div_format` which will wrap the source in `div`.  If desired custom format functions can be written to different or more complex outputs.

**Closed** 2017-04-15 20:55 UTC
Labels: Enhancement, Priority - Low

**Comment by ng28** [comment] 2018-02-08 08:59
@facelessuser Can i prepare a pull request to support the mermaid diagrams in this extension ?!

**Comment by facelessuser** [comment] 2018-02-08 14:03
I don't understand. You should be able to support mermaid without changing the core code. What changes are you wanting to make?

**Comment by ng28** [comment] 2018-02-08 17:42
Created a gist to showcase the changes made, might be you can advise me if this needed though.

https://gist.github.com/ng28/54c56b699fe3d0879a13459234f48d86

I tried to make use of custom fence with format before approaching this change set, but had no luck to make it work.

**Comment by facelessuser** [comment] 2018-02-08 17:58
These aren't used anymore:

```
        'uml_flow': [True, "Enable flowcharts - Default: True"],
        'uml_sequence': [True, "Enable sequence diagrams - Default: True"],
```

See documentation: https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#options.  So adding a mermaid specific option here does nothing.  Scan the code, we don't actually use `uml_flow` or `uml_sequence` to do anything, so adding `mermaid` will also do nothing.  Those logic behind those options were deprecated and removed.  I should go ahead remove the actual parameters as well.

So `custom_fences` is the only way to affect the extension in this way, and there should be no need to hard code a mermaid option in the library, you should be able to specify it in your mkdocs.yml file.  When I have time I can verify that with your other settings, but there is no need for a hard coded mermaid option.

**Comment by ng28** [comment] 2018-02-08 18:15
Fine @facelessuser. Check it out on your free time! I will read again the document part.

**Comment by facelessuser** [comment] 2018-02-08 18:20
If you find a specific issue with configuring (like the options not working or something) please create an issue so I can address it. But generally, I want to keep the options generic.

**Comment by facelessuser** [comment] 2018-02-08 18:34
@ng28, also, take a look at the tests that pymdown-extensions runs:

- https://github.com/facelessuser/pymdown-extensions/blob/master/tests/extensions/superfences/tests.yml#L3
- https://github.com/facelessuser/pymdown-extensions/blob/master/tests/extensions/superfences/superfences%20(custom).txt
- https://github.com/facelessuser/pymdown-extensions/blob/master/tests/extensions/superfences/superfences%20(custom).html

We do test the feature, so it should work.  Maybe the tests can help you see what you are doing wrong?

**Comment by truongln88** [comment] 2018-04-25 09:34
@facelessuser How can I switch from **fence_code_format** to **fence_div_format**? If I put the function name into the **mkdocs.yaml**, python code will get the value as string and can not execute the formatter.

**Comment by truongln88** [comment] 2018-04-25 09:35
@facelessuser I've found it here <https://github.com/facelessuser/pymdown-extensions/blob/dde0935a6ed86857445a95c4f8fb61a43fa38141/tests/extensions/superfences/tests.yml#L9>

**Comment by facelessuser** [comment] 2018-04-25 14:34
Maybe I'll make a FAQ for things like this moving forward.  I get this question now and again as a number of the extensions use function reference for customization.
