### ISSUE TITLE
Delete and Insert Extensions throw type error

### ISSUE THREAD

**Issue by Flobii** [facelessuser/pymdown-extensions#1147] opened 2020-11-16 16:19 UTC
It's probably something really obvious, but I can't seem to find it.

# Problem

When I use Caret and Tilde (DeleteSub and InsertSup) markdown throws me the following error:
```py
Traceback (most recent call last):
  File "D:/Dokumente/.Scripts/Python/markview/markview.py", line 222, in <module>
    contents()
  File "D:/Dokumente/.Scripts/Python/markview/markview.py", line 115, in contents
    markdown(content, extensions=[
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\markdown\core.py", line 387, in markdown
    return md.convert(text)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\markdown\core.py", line 268, in convert
    newRoot = treeprocessor.run(root)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\markdown\treeprocessors.py", line 396, in run
    element.insert(i, newChild)
TypeError: insert() argument 2 must be xml.etree.ElementTree.Element, not Element
```

# Used code

That's the code I use. I'm inserting them via the functions because markdown can't find them otherwise.
```py
markdown(content, extensions=[
	TocExtension(title='Table of Contents'),
	'markdown.extensions.tables',
	'markdown.extensions.footnotes',
	'markdown.extensions.fenced_code',
	'markdown.extensions.meta',
	'markdown.extensions.smarty',
	'markdown.extensions.nl2br',
	DeleteSubExtension(),
	InsertSupExtension(),
	CellRowSpanExtension(),
	MagiclinkExtension(),
	MarkExtension(),
	TabbedExtension(),
	TasklistExtension(clickable_checkbox=True, custom_checkbox=True),
	CiteExtension(),
	CriticExtension(),
	SnippetExtension(),
	SmartSymbolsExtension(),
])
```
I also tried using the Extensions all on their own, it did not change anything. It **does not* throw an error, when none of the syntax is used in the markdown file, however.

**Comment by Flobii** [comment] 2020-11-16 16:45
Sorry for closing and reopening, I thought I made a mistake, but I did not.

**Comment by facelessuser** [comment] 2020-11-16 17:10
Why are you not using this form:

```
"pymdownx.tilde"
```

And not using `extensions_configs` as described in Python Markdown documentation?

You are instantiating the extension classes without giving them the appropriate Markdown class as a parameter and the needed options. You should let Python Markdown instantiate the classes.

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by Flobii** [comment] 2020-11-17 06:51
I originally didn't do it because it wouldn't find the packages. I now tried it, but it still doesn't work. Furthermore, now a lot of other stuff doesn't work neither. (I don't think that's related) It now throws errors and I just can't understand why. I will have to try to figure it out, I'm not sure what causes it.

**Comment by facelessuser** [comment] 2020-11-17 06:58
Post what you tried. I don't know what you did the second time, but what you originally posted is completely wrong. We have numerous tests that test each extension, so I know there is no bug with loading the extension.

**Comment by Flobii** [comment] 2020-11-17 07:41
Sorry for not explaining earlier.

### Finding the error

I tried to find out, what exactly caused the error. I tried it in pure shell (it worked). I then wrote a simple file in my editor, to ensure it's not my editor. That worked as well. I then expanded my test file, recreating the structure and syntax of the file that causes problems step by step.

In that process I must have really messed something up, because it now also threw the same, original error with the TOC extension of markdown.

### Going back
 
Because no matter what I did I could not get the most basic version to run, I then tried going back a few commits until I had a working code then:
```py
markdown(content, extensions=[
	TocExtension(title='Table of Contents'),
	'markdown.extensions.tables',
	'markdown.extensions.footnotes',
	'markdown.extensions.fenced_code',
	'markdown.extensions.meta',
	'markdown.extensions.smarty',
	'markdown.extensions.nl2br',
	'cell_row_span',
	'pymdownx.magiclink',
	'pymdownx.mark',
	'pymdownx.tabbed',
	TasklistExtension(clickable_checkbox=True, custom_checkbox=True),
	'pymdownx.critic',
	'pymdownx.snippets',
	'pymdownx.smartsymbols',
])
```
I tested it this way and it works perfectly. Then I added the tilde again, and it again threw me an error. I'm not sure if this is primarily caused by the extension, but something about me using it.

### Additionaly

Thank you really much for helping me out by the way!

About importing the extensions wrong: If I want to add parameters, I have to use the function, correct?

**Comment by facelessuser** [comment] 2020-11-17 16:00
These are still wrong:

```
	TocExtension(title='Table of Contents'),
	TasklistExtension(clickable_checkbox=True, custom_checkbox=True),
```

You need to use `extensions` to specify the extension and `extension_configs` to specify the options.

Also, can you post an example snippet of failing Markdown? If you can do that, I can show you a working example (though I won't install 'cell_row_span` as I don't know what that is).

**Comment by Flobii** [comment] 2020-11-18 13:08
I will correct them asap!

The markdown I used was simply this
```markdown
# Hey

H~2~O
```
written in a file called "test.md".

But I seem to have found the error: the extension `markdown.extensions.meta` seems to have caused the errors, since I removed it everything works fine!

And `cell_row_span` is an [extension](https://github.com/Neepawa/cell_row_span) that allows for tables to span over multiple rows and lines, similar to how it is possible in rMarkdown.

**Comment by facelessuser** [comment] 2020-11-18 14:26
Okay, it sounds like you've solved your issue, so I will close this issue.

**Closed by facelessuser** 2020-11-18 14:26 UTC
Labels: T: support

**Comment by f403** [comment] 2020-11-20 11:24
Had same issue with `pymdownx.progressbar`. Attached is a possible solution.
[progressbar.txt](https://github.com/facelessuser/pymdown-extensions/files/5573187/progressbar.txt)

**Comment by facelessuser** [comment] 2020-11-20 14:25
@f403, I've seen absolutely no issue demonstrated here. The fix you've provided is simply importing Element and SubElement differently which is a completely benign change. I cannot see how the provided patch will fix anything. Unless you can demonstrate a minimal example that exposes a bug, there will be no changes made.

If you are having an issue with `etree`, maybe it is related to https://github.com/Python-Markdown/markdown/issues/950? You would have to provide some real information for me to properly assess, and if this is the case, this would be a defusedxml issue, not an issue with pymdown-extensions.

We have an entire test suite that runs on all extensions, including progressbar, and we use progressbar in our official documentation, all without issue. If there is an issue, it is most likely due to it being used incorrectly as the user in this issue discovered.

If you are having an issue, and it is not caused by incorrect usage as this issue covers, or it is not due to the defusedxml issue which is an upstream issue, please open a new issue and describe your problem in detail so we can probably guide you to a proper solution if one is available.
