### ISSUE TITLE
Edge browser - detail layout broken

### ISSUE THREAD

**Issue by DsrMedia** [facelessuser/pymdown-extensions#262] opened 2018-03-20 16:06 UTC
Hi!

In MS Edge browser the collapsible details layout is broken. Tested with the latest Edge browser (Version 41).

You can see the problem on your own page in the details section.
https://facelessuser.github.io/pymdown-extensions/extensions/details/ 

If needed I can provide a Screenshot.

Please can check & fix this issue
thx

**Comment by facelessuser** [comment] 2018-03-20 16:25
Yes, I use the [Mkdocs-Material](https://github.com/squidfunk/mkdocs-material) theme for documents.  I imagine the CSS being used by the theme isn't handling Edge proper.  Or Edge isn't handle the CSS proper.  Whatever the case may be, this is probably an upstream issue with Mkdocs-Material...or Edge.  I've never been a big fan of Microsoft's browsers.

**Comment by facelessuser** [comment] 2018-03-22 16:29
This needs to be fixed in the Mkdocs Material theme which is upstream.  I am open to a pull request for a workaround until that happens, but I do not currently have time to looking into debugging Edge.  I would even be happy if someone debugged this in Edge and could explain the issue.  I could at least then provide a targeted fix over at the Mkdocs Material theme.

But there isn't any direct work that is planned here currently for this issue.

**Comment by facelessuser** [comment] 2018-04-07 22:09
It dawned on me today what the issue is.  Edge is not rendering details as block, but as inline. I might actually be able to provide a fix for this.

**Comment by facelessuser** [comment] 2018-04-07 22:29
I'm going to close the issue here and probably fix it upstream.

**Closed by facelessuser** 2018-04-07 22:29 UTC
Labels: Documentation, Upstream

**Comment by facelessuser** [comment] 2018-04-09 14:03
Documents have been re-generated with upstream fix, so hopefully this is no longer an issue.
