### ISSUE TITLE
Snippets not working in mkDocs

### ISSUE THREAD

**Issue by hazam** [facelessuser/pymdown-extensions#1750] opened 2022-07-07 21:02 UTC
### Description

The snippet extension seems to loaded in mkdocs, but seems to never get triggered.
mkdocs 1.3.0
with or without material

### Minimal Reproduction

```
requirements.txt
mkdocs==1.3.0
```

any --8<-- never triggers.
check_paths never triggers

I'm just clueless

### Version(s) & System Info

- Operating System: Windows WSL
- Python Version: 3.9
- Package Version: 9.5, 9.4

**Comment by facelessuser** [comment] 2022-07-11 13:07
@hazam any updates providing a failing example for reproduction? I'll be giving this issue about a week more, and I'm afraid that if I hear no response, I'll have to close the issue.

**Comment by facelessuser** [comment] 2022-07-17 12:57
I am closing this issue as there has been no correspondence; therefore, we cannot when begin to guess what the issue is.

**Closed by facelessuser** 2022-07-17 12:57 UTC
Labels: T: bug, S: more-info-needed, S: triage
